package spring.domain;

// Generated 3-dic-2011 17.38.37 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Gruppopermessi generated by hbm2java
 */
public class Gruppopermessi implements java.io.Serializable {

	private int idGruppo;
	private String tipoPersona;
	private Set personas = new HashSet(0);
	private Set personas_1 = new HashSet(0);

	public Gruppopermessi() {
	}

	public Gruppopermessi(int idGruppo, String tipoPersona) {
		this.idGruppo = idGruppo;
		this.tipoPersona = tipoPersona;
	}

	public Gruppopermessi(int idGruppo, String tipoPersona, Set personas,
			Set personas_1) {
		this.idGruppo = idGruppo;
		this.tipoPersona = tipoPersona;
		this.personas = personas;
		this.personas_1 = personas_1;
	}

	public int getIdGruppo() {
		return this.idGruppo;
	}

	public void setIdGruppo(int idGruppo) {
		this.idGruppo = idGruppo;
	}

	public String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public Set getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set personas) {
		this.personas = personas;
	}

	public Set getPersonas_1() {
		return this.personas_1;
	}

	public void setPersonas_1(Set personas_1) {
		this.personas_1 = personas_1;
	}

}
