package spring.domain;

// Generated 3-dic-2011 17.38.37 by Hibernate Tools 3.3.0.GA

/**
 * SpesaId generated by hbm2java
 */
public class SpesaId implements java.io.Serializable {

	private Integer idSpesa;
	private Integer idPersona;

	public SpesaId() {
	}

	public SpesaId(int idSpesa, int idPersona) {
		this.idSpesa = idSpesa;
		this.idPersona = idPersona;
	}

	public int getIdSpesa() {
		return this.idSpesa;
	}

	public void setIdSpesa(int idSpesa) {
		this.idSpesa = idSpesa;
	}

	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpesaId))
			return false;
		SpesaId castOther = (SpesaId) other;

		return (this.getIdSpesa() == castOther.getIdSpesa())
				&& (this.getIdPersona() == castOther.getIdPersona());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSpesa();
		result = 37 * result + this.getIdPersona();
		return result;
	}

}
