package spring.domain;

// Generated 3-dic-2011 17.38.37 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Spesa generated by hbm2java
 */
@SuppressWarnings("serial")
public class Spesa implements java.io.Serializable {
	
	private Integer idPersona;	
	private Integer idSpesa;	
	private SpesaId id;
	private Date dat;
	private double importo;
	private String tipologia;
	private String descrizione;
	private Integer positiva;
	private Integer eliminato;
	private Persona persona;

	public Spesa() {
	}

	public Spesa(SpesaId id, Date dat, double importo, String tipologia, String descrizione) {
		
		this.id = id;
		this.dat = dat;
		this.importo = importo;
		this.tipologia = tipologia;
		this.descrizione=descrizione;
	}

	public Spesa(SpesaId id, Date dat, double importo, String tipologia,
			String descrizione, Integer positiva,Integer eliminato) {
		this.id = id;
		this.dat = dat;
		this.importo = importo;
		this.tipologia = tipologia;
		this.descrizione = descrizione;
		this.positiva = positiva;
		this.eliminato = eliminato;
	}
	
	public Spesa(Persona persona,Date dat, double importo, String tipologia,
			String descrizione, Integer positiva,Integer eliminato) {
		
		this.persona = persona;
		this.dat = dat;
		this.importo = importo;
		this.tipologia = tipologia;
		this.descrizione = descrizione;
		this.positiva = positiva;
		this.eliminato = eliminato;
	}
	public Integer getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

	public Integer getIdSpesa() {
		return this.idSpesa;
	}

	public void setIdSpesa(Integer idSpesa) {
		this.idSpesa = idSpesa;
	}
	public SpesaId getId() {
		return this.id;
	}

	public void setId(SpesaId id) {
		this.id = id;
	}

	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

	public double getImporto() {
		return this.importo;
	}

	public void setImporto(double importo) {
		this.importo = importo;
	}

	public String getTipologia() {
		return this.tipologia;
	}

	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Integer getEliminato() {
		return this.eliminato;
	}

	public void setEliminato(Integer eliminato) {
		this.eliminato = eliminato;
	}
	
	public Integer getPositiva() {
		return this.positiva;
	}

	public void setPositiva(Integer positiva) {
		this.positiva = positiva;
	}
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
